xbt:
  api:
    base_url: &api_base_url "https://api.chatxbt.com/store"
    key: &api_key "apiKey"
    secret: &api_secret "apiSecret"

  store:  
    kv:
      api_base_url: *api_base_url
      api_key: *api_key
      api_secret: *api_secret
    secret:
      api_base_url: *api_base_url
      api_key: *api_key
      api_secret: *api_secret
